#!/usr/bin/env bash
#
# pre-push-test-backfill.sh — LOCAL git pre-push hook that runs /test-backfill.
#
# Part of the agentic_eng artefact library. INSTALL into a target project as the
# repo's pre-push hook, e.g.:
#     ln -s "$PWD/hooks/pre-push-test-backfill.sh" .git/hooks/pre-push
#   (or copy it there, or point core.hooksPath at hooks/ and name it `pre-push`).
#
# WHAT IT DOES: when you `git push`, this fires LOCALLY, scoped to the commits you
# are pushing. It launches /test-backfill in the BACKGROUND so your push is never
# delayed, inside an isolated git WORKTREE so your working tree is never touched.
# The skill (Claude) generates tests for code new since the marker and makes a
# LOCAL commit; then this script's plain shell pushes the branch, opens a PR, and
# advances the marker tag. Humans review (/code-verifier PR mode) and merge.
#
# DESIGN INVARIANTS
#   * NEVER block the push. Phase-1 always exits 0 — the work is detached.
#   * Non-disruptive: all generation/commit happens in a throwaway worktree.
#   * Recursion-safe: pushing the backfill's own `test-backfill/*` branch (or the
#     marker tag) is detected and skipped, so it can't trigger itself.
#   * Split judgment/execution: Claude only generates + commits; push / PR / tag
#     are deterministic shell here, so the run needs NO relaxed `git push`
#     permission and settings.json is never modified.
#   * Fail open: missing `claude`/`gh`, worktree errors, test failures — all just
#     log and return; none of them ever fails the push.
#
# Everything is logged to $LOG so an async run leaves a trail you can inspect.

set -u
LOG="${TMPDIR:-/tmp}/test-backfill.log"

# =========================================================================== #
# PHASE 2 — the detached background runner (self re-invoked with --run).
#   args: <base-sha> <remote-name> <target-branch> <prev-remote-sha>
# =========================================================================== #
if [ "${1:-}" = "--run" ]; then
  base="${2:-}"; remote="${3:-origin}"; target="${4:-}"; prev="${5:-}"

  ts() { date '+%Y-%m-%d %H:%M:%S'; }
  echo "[$(ts)] backfill start: base=$base target=$target prev=$prev" >>"$LOG"

  command -v claude >/dev/null 2>&1 || { echo "[$(ts)] claude not on PATH; skipping." >>"$LOG"; exit 0; }
  repo="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
  short="$(git -C "$repo" rev-parse --short "$base" 2>/dev/null || echo "$base")"
  bfbranch="test-backfill/$short"
  wt="$(mktemp -d "${TMPDIR:-/tmp}/backfill.XXXXXX")" || exit 0

  # Isolated worktree at the exact commit being pushed — never touches the user's tree.
  if ! git -C "$repo" worktree add -b "$bfbranch" "$wt" "$base" >>"$LOG" 2>&1; then
    echo "[$(ts)] worktree add failed (branch may exist); skipping." >>"$LOG"
    rmdir "$wt" 2>/dev/null
    exit 0
  fi

  (
    cd "$wt" || exit 0
    # Hints the skill uses to scope when no marker tag exists yet (first run).
    export BACKFILL_BASE="$base" BACKFILL_PREV="$prev"
    # Generate + LOCAL commit only. git commit is gated by the test-runner hook;
    # acceptEdits lets the skill write test files without prompting.
    claude -p "/test-backfill" --permission-mode acceptEdits >>"$LOG" 2>&1

    if [ "$(git rev-parse HEAD 2>/dev/null)" != "$base" ]; then
      # Tests were generated and committed → publish (deterministic shell).
      git push -u "$remote" "$bfbranch" >>"$LOG" 2>&1
      if command -v gh >/dev/null 2>&1; then
        gh pr create --base "$target" --head "$bfbranch" \
          --title "test: backfill coverage for recent commits" \
          --body  "Generated by /test-backfill for code new since the last marker. Review with /code-verifier (PR mode)." >>"$LOG" 2>&1
      else
        echo "[$(ts)] gh missing; pushed branch $bfbranch but opened no PR." >>"$LOG"
      fi
      # Marker = the SOURCE commit backfilled, so the next push scopes past it.
      git tag -f test-backfill/last "$base" >>"$LOG" 2>&1
      git push -f "$remote" refs/tags/test-backfill/last >>"$LOG" 2>&1
      echo "[$(ts)] backfill done: branch $bfbranch, marker -> $short." >>"$LOG"
    else
      echo "[$(ts)] no tests generated (nothing recent, or a gate blocked the commit)." >>"$LOG"
    fi
  )

  git -C "$repo" worktree remove --force "$wt" >>"$LOG" 2>&1
  git -C "$repo" worktree prune >>"$LOG" 2>&1
  exit 0
fi

# =========================================================================== #
# PHASE 1 — the pre-push hook itself. MUST exit 0 (never block the push).
#   git passes: <remote-name> <remote-url> as $1 $2, and on stdin one line per
#   pushed ref: "<local-ref> <local-sha> <remote-ref> <remote-sha>".
# =========================================================================== #
remote_name="${1:-origin}"
zero="0000000000000000000000000000000000000000"

# Pick the first ordinary branch being pushed; skip our own branch/tag pushes
# (recursion guard) and deletions.
base=""; target=""; prev=""
while read -r local_ref local_sha remote_ref remote_sha; do
  [ -n "$local_ref" ] || continue
  case "$local_ref" in
    refs/heads/test-backfill/*) continue ;;     # our own backfill branch — skip
    refs/heads/*) : ;;                            # an ordinary branch — candidate
    *) continue ;;                                # tags (incl. marker), notes — skip
  esac
  [ "$local_sha" = "$zero" ] && continue          # branch deletion — nothing to test
  base="$local_sha"
  target="${remote_ref#refs/heads/}"
  prev="$remote_sha"; [ "$prev" = "$zero" ] && prev=""   # new branch: no prior tip
  break
done

# Nothing worth backfilling, or claude unavailable → do nothing, allow the push.
[ -n "$base" ] || exit 0
command -v claude >/dev/null 2>&1 || exit 0

# Detach the runner so the push proceeds immediately. All fds redirected and
# stdin closed so git does not wait on it.
( nohup "$0" --run "$base" "$remote_name" "$target" "$prev" >>"$LOG" 2>&1 </dev/null & )

exit 0
